version: '3.3'

services:
  database:
    container_name: pg_db
    build: .
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password@7979
    - POSTGRES_DB=db
    volumes:
    - ./db_data:/var/lib/postgresql
    ports:
    - "5432:5432"


volumes:
  db_data:
